kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apache-manager-binding
  namespace: apache
subjects:
  - kind: User
    name: apache-user
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: apache-manager
  apiGroup: rbac.authorization.k8s.io
#this file binds the apache-manager role to the apache-user service account in the apache namespace
#this allows the apache-user service account to perform the actions defined in the apache-manager role
