kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apache-manager
  namespace: apache
rules:
  - apiGroups: ["", "apps", "extensions", "rbac.authorization.k8s.io", "batch"]
    resources:
      [
        "pods",
        "services",
        "endpoints",
        "configmaps",
        "deployments",
        "replicasets",
      ]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
#this file creates a role named apache-manager in the apache namespace
#this role allows managing pods, services, endpoints, configmaps, deployments, and replicasets
#the apache-manager role can perform get, list, watch, create, update, patch, and delete actions on these resources
