kind: ServiceAccount
apiVersion: v1
metadata:
  name: apache-user
  namespace: apache
#this file creates a service account named apache-user in the apache namespace
#this service account can be used to authenticate as apache-user when performing kubectl commands
